version: '3'
services:
  web:
    image: "docker-node-mongo-todo-app"
    build: .
    command: "node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
